/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function sum(a: number, b: number): number
export declare function sendRightClickAt(x: number, y: number): void
export declare function sendLeftClickAt(x: number, y: number): void
export declare function sendMiddleClickAt(x: number, y: number): void
